### ISSUE TITLE
Unable to install sassc-ruby on macOS Mojave 10.14.4

### ISSUE THREAD

**Issue by mikel** [sass/sassc-ruby#115]
I received the attached stack trace when trying to install `sassc-ruby` after upgrading to Mojave 10.14.4.

This was fixed by running a `brew upgrade`.

Just posting here for others if they run into it.

```
Installing sassc 2.0.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1/ext
/Users/mikel/.rvm/rubies/ruby-2.3.3/bin/ruby -rrubygems /Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/rake-12.3.2/exe/rake RUBYARCHDIR=/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/extensions/x86_64-darwin-18/2.3.0/sassc-2.0.1 RUBYLIBDIR=/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/extensions/x86_64-darwin-18/2.3.0/sassc-2.0.1
cd libsass
make lib/libsass.so
mkdir lib
cc -Wall -O2 -I /Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1/ext/libsass/include -stdlib=libc++ -fPIC -fPIC -c -o src/cencode.o src/cencode.c
src/cencode.c:50:5: warning: declaration does not declare anything [-Wmissing-declarations]
                                __attribute__ ((fallthrough));
                                ^
src/cencode.c:64:5: warning: declaration does not declare anything [-Wmissing-declarations]
                                __attribute__ ((fallthrough));
                                ^
2 warnings generated.

<SNIP>

src/error_handling.o src/memory/SharedPtr.o src/utf8_string.o src/base64vlq.o -lm -lstdc++ -ldl
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const", referenced from:
      Sass::Emitter::append_optional_space() in emitter.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const", referenced from:
      Sass::Simple_Selector::Simple_Selector(Sass::ParserState, std::__1::basic_string<char, 

<SNIP>

      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libsass.so] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so...]
/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1/lib/tasks/libsass.rb:31:in `block (2 levels) in <top (required)>'
/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1/lib/tasks/libsass.rb:13:in `block (3 levels) in <top (required)>'
/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1/lib/tasks/libsass.rb:12:in `block (2 levels) in <top (required)>'
/Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/rake-12.3.2/exe/rake:27:in `<main>'
Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/mikel/.rvm/gems/ruby-2.3.3@enlight/gems/sassc-2.0.1 for inspection.
Results logged to /Users/mikel/.rvm/gems/ruby-2.3.3@enlight/extensions/x86_64-darwin-18/2.3.0/sassc-2.0.1/gem_make.out

```

**Comment by glebm** [comment]
You should always run `brew upgrade` and `brew doctor` after upgrading macOS. Has nothing to do with this gem.

**Comment by glebm** [comment]
https://docs.brew.sh/Common-Issues#upgrading-macos
