### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by rubenswieringa** [sass/sassc-ruby#26]
`bundle exec rake test` makes the following 3 tests fail. Seeing as Travis is still happy, I'm guessing there's something I can do to make them pass on my machine, but what that is is not obvious to me. Any ideas?

```
  1) Error:
SassC::FunctionsTest#test_functions_may_accept_sass_color_type:
SassC::SyntaxError: Error: error in C function nice_color_argument: uninitialized constant Sass::Script::Value::Number

       Backtrace:
       	stdin:1, in function `nice_color_argument`
       	stdin:1
        on line 1 of stdin
>>         div { color: nice_color_argument(red); }
   ---------------------^

    /Users/ruben.swieringa/Development/sassc-ruby/lib/sassc/engine.rb:41:in `render'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:124:in `assert_sass'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:81:in `test_functions_may_accept_sass_color_type'


  2) Error:
SassC::FunctionsTest#test_function_that_returns_a_color:
SassC::SyntaxError: Error: error in C function returns-a-color: uninitialized constant Sass::Script::Value::Number

       Backtrace:
       	stdin:1, in function `returns-a-color`
       	stdin:1
        on line 1 of stdin
>>         div { background: returns-a-color(); }
   --------------------------^

    /Users/ruben.swieringa/Development/sassc-ruby/lib/sassc/engine.rb:41:in `render'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:124:in `assert_sass'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:59:in `test_function_that_returns_a_color'


  3) Error:
SassC::FunctionsTest#test_function_that_returns_a_sass_value:
SassC::SyntaxError: Error: error in C function returns-sass-value: uninitialized constant Sass::Script::Value::Number

       Backtrace:
       	stdin:1, in function `returns-sass-value`
       	stdin:1
        on line 1 of stdin
>>         div { background: returns-sass-value(); }
   --------------------------^

    /Users/ruben.swieringa/Development/sassc-ruby/lib/sassc/engine.rb:41:in `render'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:124:in `assert_sass'
    /Users/ruben.swieringa/Development/sassc-ruby/test/functions_test.rb:112:in `test_function_that_returns_a_sass_value'
```

\* I'm currently up-to-date with HEAD at `7c627a67900b98485528149124215af4ea38d575`, ruby version is at `2.1.5p273`

**Comment by rubenswieringa** [comment]
**PS.** I'm on OSX 10.10.5

**Comment by rubenswieringa** [comment]
Full log (including compilation warnings): **[bundle exec rake test.txt](https://github.com/sass/sassc-ruby/files/61172/bundle.exec.rake.test.txt)**

**Comment by bolandrm** [comment]
I'm on the same version of OSX as you, and I have not seen any issues like this.  Could you please try cloning a fresh version of the repo and trying again?  (we just bumped to libsass 3.3.2).

I do not receive those warnings when compiling, so that likely has something to do with it.

**Comment by rubenswieringa** [comment]
Alright, my bad I guess – fresh checkout helped. Sorry for the confusion.
