### ISSUE TITLE
Unable to install on CentOS 6.7

### ISSUE THREAD

**Issue by KaptajnKold** [sass/sassc-ruby#37]
I get the following error, when I try to install on CentOS 6.7. Am I missing some dependency? Any help would be much appreciated 😃

```
gem install sassc
Building native extensions.  This could take a while...
ERROR:  Error installing sassc:
    ERROR: Failed to build gem native extension.

    /var/lib/jenkins/.rbenv/versions/2.2.3/bin/ruby -rubygems /var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/sassc-1.8.4 RUBYLIBDIR=/var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/sassc-1.8.4
cd libsass
make lib/libsass.so
mkdir lib
cc -Wall -O2 -I /var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sassc-1.8.4/ext/libsass/include -fPIC -fPIC -c -o src/cencode.o src/cencode.c
g++ -Wall -O2 -std=c++0x -I /var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sassc-1.8.4/ext/libsass/include -fPIC -fPIC -c -o src/ast.o src/ast.cpp
In file included from src/ast.cpp:2:
src/ast.hpp: In member function 'virtual size_t Sass::Vectorized<T>::hash()':
src/ast.hpp:257: error: expected initializer before ':' token
src/ast.hpp:260: error: expected primary-expression before '}' token
src/ast.hpp:260: error: expected ';' before '}' token
src/ast.hpp:260: error: expected primary-expression before '}' token
src/ast.hpp:260: error: expected ')' before '}' token
src/ast.hpp:260: error: expected primary-expression before '}' token
src/ast.hpp:260: error: expected ';' before '}' token
src/ast.hpp: In constructor 'Sass::Hashed::Hashed(size_t)':
src/ast.hpp:291: error: 'class std::unordered_map<Sass::Expression*, Sass::Expression*, std::hash<Sass::Expression*>, std::equal_to<Sass::Expression*>, std::allocator<std::pair<Sass::Expression* const, Sass::Expression*> > >' has no member named 'reserve'
src/ast.hpp: In member function 'Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)':
src/ast.hpp:320: error: expected initializer before ':' token
src/ast.hpp:324: error: could not convert 'Sass::Hashed::reset_duplicate_key()' to 'bool'
src/ast.hpp:325: error: expected primary-expression before 'return'
src/ast.hpp:325: error: expected ')' before 'return'
src/ast.hpp: In member function 'virtual size_t Sass::Map::hash()':
src/ast.hpp:916: error: expected initializer before ':' token
src/ast.hpp:920: error: expected primary-expression before '}' token
src/ast.hpp:920: error: expected ';' before '}' token
src/ast.hpp:920: error: expected primary-expression before '}' token
src/ast.hpp:920: error: expected ')' before '}' token
src/ast.hpp:920: error: expected primary-expression before '}' token
src/ast.hpp:920: error: expected ';' before '}' token
src/ast.hpp: In member function 'virtual size_t Sass::Function_Call::hash()':
src/ast.hpp:1206: error: expected initializer before ':' token
src/ast.hpp:1208: error: expected primary-expression before '}' token
src/ast.hpp:1208: error: expected ';' before '}' token
src/ast.hpp:1208: error: expected primary-expression before '}' token
src/ast.hpp:1208: error: expected ')' before '}' token
src/ast.hpp:1208: error: expected primary-expression before '}' token
src/ast.hpp:1208: error: expected ';' before '}' token
src/ast.hpp: In member function 'virtual size_t Sass::Number::hash()':
src/ast.hpp:1335: error: expected initializer before ':' token
src/ast.hpp:1337: error: expected primary-expression before 'for'
src/ast.hpp:1337: error: expected ';' before 'for'
src/ast.hpp:1337: error: expected primary-expression before 'for'
src/ast.hpp:1337: error: expected ')' before 'for'
src/ast.hpp:1337: error: expected initializer before ':' token
src/ast.hpp:1339: error: expected primary-expression before '}' token
src/ast.hpp:1339: error: expected ';' before '}' token
src/ast.hpp:1339: error: expected primary-expression before '}' token
src/ast.hpp:1339: error: expected ')' before '}' token
src/ast.hpp:1339: error: expected primary-expression before '}' token
src/ast.hpp:1339: error: expected ';' before '}' token
src/ast.hpp: In member function 'bool Sass::String_Schema::has_interpolants()':
src/ast.hpp:1473: error: expected initializer before ':' token
src/ast.hpp:1476: error: expected primary-expression before 'return'
src/ast.hpp:1476: error: expected ';' before 'return'
src/ast.hpp:1476: error: expected primary-expression before 'return'
src/ast.hpp:1476: error: expected ')' before 'return'
src/ast.hpp: In member function 'virtual size_t Sass::String_Schema::hash()':
src/ast.hpp:1482: error: expected initializer before ':' token
src/ast.hpp:1484: error: expected primary-expression before '}' token
src/ast.hpp:1484: error: expected ';' before '}' token
src/ast.hpp:1484: error: expected primary-expression before '}' token
src/ast.hpp:1484: error: expected ')' before '}' token
src/ast.hpp:1484: error: expected primary-expression before '}' token
src/ast.hpp:1484: error: expected ';' before '}' token
In file included from src/ast.cpp:2:
src/ast.hpp: In member function 'virtual size_t Sass::Compound_Selector::hash()':
src/ast.hpp:2244: error: 'template<class T> class Sass::Vectorized' used without template parameters
src/ast.hpp: In member function 'virtual size_t Sass::Selector_List::hash()':
src/ast.hpp:2466: error: 'template<class T> class Sass::Vectorized' used without template parameters
src/ast.cpp: In member function 'virtual bool Sass::Compound_Selector::has_parent_ref()':
src/ast.cpp:62: error: expected initializer before ':' token
src/ast.cpp:65: error: expected primary-expression before 'return'
src/ast.cpp:65: error: expected ';' before 'return'
src/ast.cpp:65: error: expected primary-expression before 'return'
src/ast.cpp:65: error: expected ')' before 'return'
src/ast.cpp: In member function 'virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)':
src/ast.cpp:539: error: expected initializer before ':' token
src/ast.cpp:542: error: expected primary-expression before 'return'
src/ast.cpp:542: error: expected ';' before 'return'
src/ast.cpp:542: error: expected primary-expression before 'return'
src/ast.cpp:542: error: expected ')' before 'return'
src/ast.cpp: In member function 'Sass::Selector_List* Sass::Complex_Selector::parentize(Sass::Selector_List*, Sass::Context&)':
src/ast.cpp:1048: error: expected initializer before ':' token
src/ast.cpp:2066: error: expected primary-expression at end of input
src/ast.cpp:2066: error: expected ';' at end of input
src/ast.cpp:2066: error: expected primary-expression at end of input
src/ast.cpp:2066: error: expected ')' at end of input
src/ast.cpp:2066: error: expected statement at end of input
src/ast.cpp:2066: error: expected '}' at end of input
src/ast.cpp:2066: error: expected '}' at end of input
src/ast.cpp: At global scope:
src/ast.cpp:2066: error: expected '}' at end of input
src/units.hpp:10: warning: 'Sass::PI' defined but not used
make: *** [src/ast.o] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so...]

Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sassc-1.8.4 for inspection.
Results logged to /var/lib/jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/sassc-1.8.4/gem_make.out
```

**Comment by bolandrm** [comment]
Looks like it's failing to build LibSass.  I'd recommend pulling down [LibSass](https://github.com/sass/libsass) itself and trying to get it to build.  https://github.com/sass/libsass/blob/master/docs/build.md

**Comment by GUI** [comment]
In case anyone else runs into this same issue, I believe this is because libsass needs GCC 4.6 or higher in order to compile (https://github.com/sass/libsass/pull/848). CentOS/RHEL 6 uses GCC 4.4, so unless you want to mess around with manually installing another newer version of GCC, I'm not sure there's a simple solution to getting libsass or the sassc gem running under CentOS 6.

**Comment by georgekaf** [comment]
The only solution to install this gem or even compile the libsass library (https://github.com/sass/sassc/blob/master/docs/building/unix-instructions.md) in centos 6.x was this 
for me

```bash
#cd /etc/yum.repos.d
#wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo 
#yum --enablerepo=testing-1.1-devtools-6 install devtoolset-1.1-gcc devtoolset-1.1-gcc-c++
```
and add the following in my .bash_profile

```bash
export CC=/opt/centos/devtoolset-1.1/root/usr/bin/gcc  
export CPP=/opt/centos/devtoolset-1.1/root/usr/bin/cpp
export CXX=/opt/centos/devtoolset-1.1/root/usr/bin/c++
```

reload the bash_profile and then the compiling was successful.

**Comment by plentz** [comment]
I'm having the same problem even with GC 4.8
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
Command gcc -v exited successfully with status 0.
Took 0.00512 seconds.
```

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/go/.bundled-gems/gems/sassc-1.10.1/ext
/opt/local/rbenv/versions/2.3.0/bin/ruby -rubygems
/var/go/.bundled-gems/gems/rake-11.3.0/exe/rake
RUBYARCHDIR=/var/go/.bundled-gems/extensions/x86_64-linux/2.3.0-static/sassc-1.10.1
RUBYLIBDIR=/var/go/.bundled-gems/extensions/x86_64-linux/2.3.0-static/sassc-1.10.1
cd libsass
make lib/libsass.so
mkdir lib
cc -Wall -O2 -I /var/go/.bundled-gems/gems/sassc-1.10.1/ext/libsass/include
-fPIC -fPIC -c -o src/cencode.o src/cencode.c
g++ -Wall -O2 -std=c++0x -I
/var/go/.bundled-gems/gems/sassc-1.10.1/ext/libsass/include -fPIC -fPIC -c -o
src/ast.o src/ast.cpp
In file included from src/ast.cpp:2:
src/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
src/ast.hpp:257: error: expected initializer before ‘:’ token
src/ast.hpp:260: error: expected primary-expression before ‘}’ token
src/ast.hpp:260: error: expected ‘;’ before ‘}’ token
src/ast.hpp:260: error: expected primary-expression before ‘}’ token
src/ast.hpp:260: error: expected ‘)’ before ‘}’ token
src/ast.hpp:260: error: expected primary-expression before ‘}’ token
src/ast.hpp:260: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
src/ast.hpp:307: error: ‘class std::unordered_map<Sass::Expression*,
Sass::Expression*, Sass::Hashed::HashExpression,
Sass::Hashed::CompareExpression, std::allocator<std::pair<Sass::Expression*
const, Sass::Expression*> > >’ has no member named ‘reserve’
src/ast.hpp: In member function ‘Sass::Hashed&
Sass::Hashed::operator+=(Sass::Hashed*)’:
src/ast.hpp:336: error: expected initializer before ‘:’ token
src/ast.hpp:340: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’
to ‘bool’
src/ast.hpp:341: error: expected primary-expression before ‘return’
src/ast.hpp:341: error: expected ‘)’ before ‘return’
src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
src/ast.hpp:936: error: expected initializer before ‘:’ token
src/ast.hpp:940: error: expected primary-expression before ‘}’ token
src/ast.hpp:940: error: expected ‘;’ before ‘}’ token
src/ast.hpp:940: error: expected primary-expression before ‘}’ token
src/ast.hpp:940: error: expected ‘)’ before ‘}’ token
src/ast.hpp:940: error: expected primary-expression before ‘}’ token
src/ast.hpp:940: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
src/ast.hpp:1232: error: expected initializer before ‘:’ token
src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
src/ast.hpp:1234: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
src/ast.hpp:1234: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
src/ast.hpp:1234: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
src/ast.hpp:1361: error: expected initializer before ‘:’ token
src/ast.hpp:1363: error: expected primary-expression before ‘for’
src/ast.hpp:1363: error: expected ‘;’ before ‘for’
src/ast.hpp:1363: error: expected primary-expression before ‘for’
src/ast.hpp:1363: error: expected ‘)’ before ‘for’
src/ast.hpp:1363: error: expected initializer before ‘:’ token
src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
src/ast.hpp:1365: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
src/ast.hpp:1365: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
src/ast.hpp:1365: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘bool Sass::String_Schema::has_interpolants()’:
src/ast.hpp:1502: error: expected initializer before ‘:’ token
src/ast.hpp:1505: error: expected primary-expression before ‘return’
src/ast.hpp:1505: error: expected ‘;’ before ‘return’
src/ast.hpp:1505: error: expected primary-expression before ‘return’
src/ast.hpp:1505: error: expected ‘)’ before ‘return’
src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
src/ast.hpp:1514: error: expected initializer before ‘:’ token
src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
src/ast.hpp:1516: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
src/ast.hpp:1516: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
src/ast.hpp:1516: error: expected ‘;’ before ‘}’ token
In file included from src/ast.cpp:2:
src/ast.hpp: In member function ‘virtual size_t
Sass::Compound_Selector::hash()’:
src/ast.hpp:2261: error: ‘template<class T> class Sass::Vectorized’ used without
template parameters
src/ast.hpp: In member function ‘virtual size_t Sass::Selector_List::hash()’:
src/ast.hpp:2488: error: ‘template<class T> class Sass::Vectorized’ used without
template parameters
src/ast.hpp: In member function ‘virtual void
Sass::Selector_List::set_media_block(Sass::Media_Block*)’:
src/ast.hpp:2505: error: expected initializer before ‘:’ token
src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
src/ast.hpp:2508: error: expected ‘;’ before ‘}’ token
src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
src/ast.hpp:2508: error: expected ‘)’ before ‘}’ token
src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
src/ast.hpp:2508: error: expected ‘;’ before ‘}’ token
src/ast.cpp: In function ‘std::string& Sass::str_ltrim(std::string&)’:
src/ast.cpp:33: error: expected primary-expression before ‘[’ token
src/ast.cpp:33: error: expected primary-expression before ‘]’ token
src/ast.cpp:33: error: expected primary-expression before ‘char’
src/ast.cpp:33: error: unable to deduce ‘auto’ from ‘<expression error>’
src/ast.cpp: In function ‘std::string& Sass::str_rtrim(std::string&)’:
src/ast.cpp:40: error: expected primary-expression before ‘[’ token
src/ast.cpp:40: error: expected primary-expression before ‘]’ token
src/ast.cpp:40: error: expected primary-expression before ‘char’
src/ast.cpp:40: error: unable to deduce ‘auto’ from ‘<expression error>’
src/ast.cpp: In member function ‘virtual bool
Sass::Compound_Selector::has_parent_ref()’:
src/ast.cpp:139: error: expected initializer before ‘:’ token
src/ast.cpp:142: error: expected primary-expression before ‘return’
src/ast.cpp:142: error: expected ‘;’ before ‘return’
src/ast.cpp:142: error: expected primary-expression before ‘return’
src/ast.cpp:142: error: expected ‘)’ before ‘return’
src/ast.cpp: In member function ‘virtual bool
Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*,
std::string)’:
src/ast.cpp:661: error: expected initializer before ‘:’ token
src/ast.cpp:664: error: expected primary-expression before ‘return’
src/ast.cpp:664: error: expected ‘;’ before ‘return’
src/ast.cpp:664: error: expected primary-expression before ‘return’
src/ast.cpp:664: error: expected ‘)’ before ‘return’
src/ast.cpp: In member function ‘Sass::Selector_List*
Sass::Complex_Selector::parentize(Sass::Selector_List*, Sass::Context&)’:
src/ast.cpp:1171: error: expected initializer before ‘:’ token
src/ast.cpp:2216: error: expected primary-expression at end of input
src/ast.cpp:2216: error: expected ‘;’ at end of input
src/ast.cpp:2216: error: expected primary-expression at end of input
src/ast.cpp:2216: error: expected ‘)’ at end of input
src/ast.cpp:2216: error: expected statement at end of input
src/ast.cpp:2216: error: expected ‘}’ at end of input
src/ast.cpp:2216: error: expected ‘}’ at end of input
src/ast.cpp: At global scope:
src/ast.cpp:2216: error: expected ‘}’ at end of input
src/units.hpp:10: warning: ‘Sass::PI’ defined but not used
make: *** [src/ast.o] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so...]
/var/go/.bundled-gems/gems/sassc-1.10.1/lib/tasks/libsass.rb:29:in `block (2
levels) in <top (required)>'
/var/go/.bundled-gems/gems/sassc-1.10.1/lib/tasks/libsass.rb:11:in `block (3
levels) in <top (required)>'
/var/go/.bundled-gems/gems/sassc-1.10.1/lib/tasks/libsass.rb:10:in `block (2
levels) in <top (required)>'
/var/go/.bundled-gems/gems/rake-11.3.0/exe/rake:27:in `<main>'
Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/go/.bundled-gems/gems/sassc-1.10.1 for
inspection.
Results logged to
/var/go/.bundled-gems/extensions/x86_64-linux/2.3.0-static/sassc-1.10.1/gem_make.out

An error occurred while installing sassc (1.10.1), and Bundler cannot continue.
```

**Comment by bolandrm** [comment]
Closing this as a stale issue which I am unable to resolve

**Comment by toncid** [comment]
FWIW, this is what works for me:

```
# cd /etc/yum.repos.d
# wget https://people.centos.org/tru/devtools-2/devtools-2.repo
# yum --enablerepo=testing-devtools-2-centos-6 install devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-binutils

$ cd /path/to/rails_app
$ sudo -s
# scl enable devtoolset-2 bash
# gem install sassc
```
