### ISSUE TITLE
Sassc 0.11.1 doesn't compile

### ISSUE THREAD

**Issue by fap-** [sass/sassc-ruby#62]
It's probably a problem with my setup but I couldn't find anything about this in the readme.
Here is my error message:

```
> gem install sassc -v '1.11.1'
Fetching: sassc-1.11.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    current directory: /home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/ext
/package/host/localhost/ruby-2.3.1/bin/ruby -rubygems /package/host/localhost/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/exe/rake RUBYARCHDIR=/home/fap/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/sassc-1.11.1 RUBYLIBDIR=/home/fap/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/sassc-1.11.1
cd libsass
make lib/libsass.so
mkdir lib
cc -Wall -O2 -I /home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/ext/libsass/include -fPIC -fPIC -c -o src/cencode.o src/cencode.c
g++ -Wall -O2 -std=c++0x -I /home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/ext/libsass/include -fPIC -fPIC -c -o src/ast.o src/ast.cpp
In file included from src/ast.cpp:2:
src/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
src/ast.hpp:264: error: expected initializer before ‘:’ token
src/ast.hpp:267: error: expected primary-expression before ‘}’ token
src/ast.hpp:267: error: expected ‘;’ before ‘}’ token
src/ast.hpp:267: error: expected primary-expression before ‘}’ token
src/ast.hpp:267: error: expected ‘)’ before ‘}’ token
src/ast.hpp:267: error: expected primary-expression before ‘}’ token
src/ast.hpp:267: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
src/ast.hpp:314: error: ‘class Sass::Hashed::ExpressionMap’ has no member named ‘reserve’
src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
src/ast.hpp:343: error: expected initializer before ‘:’ token
src/ast.hpp:347: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
src/ast.hpp:348: error: expected primary-expression before ‘return’
src/ast.hpp:348: error: expected ‘)’ before ‘return’
In file included from src/ast.cpp:2:
src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
src/ast.hpp:933: error: expected initializer before ‘:’ token
src/ast.hpp:937: error: expected primary-expression before ‘}’ token
src/ast.hpp:937: error: expected ‘;’ before ‘}’ token
src/ast.hpp:937: error: expected primary-expression before ‘}’ token
src/ast.hpp:937: error: expected ‘)’ before ‘}’ token
src/ast.hpp:937: error: expected primary-expression before ‘}’ token
src/ast.hpp:937: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
src/ast.hpp:1226: error: expected initializer before ‘:’ token
src/ast.hpp:1228: error: expected primary-expression before ‘}’ token
src/ast.hpp:1228: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1228: error: expected primary-expression before ‘}’ token
src/ast.hpp:1228: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1228: error: expected primary-expression before ‘}’ token
src/ast.hpp:1228: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
src/ast.hpp:1355: error: expected initializer before ‘:’ token
src/ast.hpp:1357: error: expected primary-expression before ‘for’
src/ast.hpp:1357: error: expected ‘;’ before ‘for’
src/ast.hpp:1357: error: expected primary-expression before ‘for’
src/ast.hpp:1357: error: expected ‘)’ before ‘for’
src/ast.hpp:1357: error: expected initializer before ‘:’ token
src/ast.hpp:1359: error: expected primary-expression before ‘}’ token
src/ast.hpp:1359: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1359: error: expected primary-expression before ‘}’ token
src/ast.hpp:1359: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1359: error: expected primary-expression before ‘}’ token
src/ast.hpp:1359: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘bool Sass::String_Schema::has_interpolants()’:
src/ast.hpp:1496: error: expected initializer before ‘:’ token
src/ast.hpp:1499: error: expected primary-expression before ‘return’
src/ast.hpp:1499: error: expected ‘;’ before ‘return’
src/ast.hpp:1499: error: expected primary-expression before ‘return’
src/ast.hpp:1499: error: expected ‘)’ before ‘return’
src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
src/ast.hpp:1508: error: expected initializer before ‘:’ token
src/ast.hpp:1510: error: expected primary-expression before ‘}’ token
src/ast.hpp:1510: error: expected ‘;’ before ‘}’ token
src/ast.hpp:1510: error: expected primary-expression before ‘}’ token
src/ast.hpp:1510: error: expected ‘)’ before ‘}’ token
src/ast.hpp:1510: error: expected primary-expression before ‘}’ token
src/ast.hpp:1510: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual size_t Sass::SimpleSequence_Selector::hash()’:
src/ast.hpp:2327: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
src/ast.hpp: In member function ‘virtual size_t Sass::CommaSequence_Selector::hash()’:
src/ast.hpp:2584: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
src/ast.hpp: In member function ‘virtual void Sass::CommaSequence_Selector::set_media_block(Sass::Media_Block*)’:
src/ast.hpp:2601: error: expected initializer before ‘:’ token
src/ast.hpp:2604: error: expected primary-expression before ‘}’ token
src/ast.hpp:2604: error: expected ‘;’ before ‘}’ token
src/ast.hpp:2604: error: expected primary-expression before ‘}’ token
src/ast.hpp:2604: error: expected ‘)’ before ‘}’ token
src/ast.hpp:2604: error: expected primary-expression before ‘}’ token
src/ast.hpp:2604: error: expected ‘;’ before ‘}’ token
src/ast.hpp: In member function ‘virtual bool Sass::CommaSequence_Selector::has_wrapped_selector()’:
src/ast.hpp:2606: error: expected initializer before ‘:’ token
src/ast.hpp:2609: error: expected primary-expression before ‘return’
src/ast.hpp:2609: error: expected ‘;’ before ‘return’
src/ast.hpp:2609: error: expected primary-expression before ‘return’
src/ast.hpp:2609: error: expected ‘)’ before ‘return’
src/ast.hpp: In member function ‘virtual bool Sass::CommaSequence_Selector::has_placeholder()’:
src/ast.hpp:2612: error: expected initializer before ‘:’ token
src/ast.hpp:2615: error: expected primary-expression before ‘return’
src/ast.hpp:2615: error: expected ‘;’ before ‘return’
src/ast.hpp:2615: error: expected primary-expression before ‘return’
src/ast.hpp:2615: error: expected ‘)’ before ‘return’
src/ast.cpp: In function ‘std::string& Sass::str_ltrim(std::string&)’:
src/ast.cpp:33: error: expected primary-expression before ‘[’ token
src/ast.cpp:33: error: expected primary-expression before ‘]’ token
src/ast.cpp:33: error: expected primary-expression before ‘char’
src/ast.cpp:33: error: unable to deduce ‘auto’ from ‘<expression error>’
src/ast.cpp: In function ‘std::string& Sass::str_rtrim(std::string&)’:
src/ast.cpp:40: error: expected primary-expression before ‘[’ token
src/ast.cpp:40: error: expected primary-expression before ‘]’ token
src/ast.cpp:40: error: expected primary-expression before ‘char’
src/ast.cpp:40: error: unable to deduce ‘auto’ from ‘<expression error>’
src/ast.cpp: In member function ‘virtual void Sass::Arguments::set_delayed(bool)’:
src/ast.cpp:85: error: expected initializer before ‘:’ token
src/ast.cpp:89: error: expected primary-expression before ‘}’ token
src/ast.cpp:89: error: expected ‘)’ before ‘}’ token
src/ast.cpp:89: error: expected primary-expression before ‘}’ token
src/ast.cpp:89: error: expected ‘;’ before ‘}’ token
src/ast.cpp: In member function ‘virtual bool Sass::SimpleSequence_Selector::has_parent_ref()’:
src/ast.cpp:159: error: expected initializer before ‘:’ token
src/ast.cpp:162: error: expected primary-expression before ‘return’
src/ast.cpp:162: error: expected ‘;’ before ‘return’
src/ast.cpp:162: error: expected primary-expression before ‘return’
src/ast.cpp:162: error: expected ‘)’ before ‘return’
src/ast.cpp: In member function ‘virtual bool Sass::SimpleSequence_Selector::has_real_parent_ref()’:
src/ast.cpp:167: error: expected initializer before ‘:’ token
src/ast.cpp:170: error: expected primary-expression before ‘return’
src/ast.cpp:170: error: expected ‘;’ before ‘return’
src/ast.cpp:170: error: expected primary-expression before ‘return’
src/ast.cpp:170: error: expected ‘)’ before ‘return’
src/ast.cpp: In member function ‘virtual bool Sass::SimpleSequence_Selector::is_superselector_of(Sass::CommaSequence_Selector*, std::string)’:
src/ast.cpp:697: error: expected initializer before ‘:’ token
src/ast.cpp:700: error: expected primary-expression before ‘return’
src/ast.cpp:700: error: expected ‘;’ before ‘return’
src/ast.cpp:700: error: expected primary-expression before ‘return’
src/ast.cpp:700: error: expected ‘)’ before ‘return’
src/ast.cpp: In member function ‘Sass::CommaSequence_Selector* Sass::Sequence_Selector::resolve_parent_refs(Sass::Context&, Sass::CommaSequence_Selector*, bool)’:
src/ast.cpp:1247: error: expected initializer before ‘:’ token
src/ast.cpp:2325: error: expected primary-expression at end of input
src/ast.cpp:2325: error: expected ‘;’ at end of input
src/ast.cpp:2325: error: expected primary-expression at end of input
src/ast.cpp:2325: error: expected ‘)’ at end of input
src/ast.cpp:2325: error: expected statement at end of input
src/ast.cpp:2325: error: expected ‘}’ at end of input
src/ast.cpp:2325: error: expected ‘}’ at end of input
src/ast.cpp: At global scope:
src/ast.cpp:2325: error: expected ‘}’ at end of input
src/units.hpp:10: warning: ‘Sass::PI’ defined but not used
make: *** [src/ast.o] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so...]
/home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/lib/tasks/libsass.rb:29:in `block (2 levels) in <top (required)>'
/home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/lib/tasks/libsass.rb:11:in `block (3 levels) in <top (required)>'
/home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1/lib/tasks/libsass.rb:10:in `block (2 levels) in <top (required)>'
Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/fap/.gem/ruby/2.3.0/gems/sassc-1.11.1 for inspection.
Results logged to /home/fap/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/sassc-1.11.1/gem_make.out
```

**Comment by fap-** [comment]
Found the solution here: https://github.com/sass/sassc-ruby/issues/37
I had to update my gcc version to compile libsass successfully.
