### ISSUE TITLE
uninitialized constant Sass::Script::String

### ISSUE THREAD

**Issue by joelim01** [sass/sassc-ruby#67]
Hello,
Getting the following when compiling assets in my rails 4 app:
`SassC::SyntaxError - Error: error in C function image-url: uninitialized constant Sass::Script::String`

It is being thrown when Rails reaches the following line in a .scss file:
`background-image: image-url("images/image.png");`

Here's a bit of the backtrace:
```
sassc () lib/sassc/engine.rb:47:in `render'
sassc-rails () lib/sassc/rails/template.rb:34:in `block in call'
sprockets () lib/sprockets/utils.rb:167:in `module_include'
sassc-rails () lib/sassc/rails/template.rb:33:in `call'
sprockets () lib/sprockets/sass_processor.rb:30:in `call'
sprockets () lib/sprockets/processor_utils.rb:75:in `call_processor'
```

Compiling the same scss file in a fresh 'test-app' using the same version of the gems is successful.

It is also worth mentioning that removing the 'jquery-fileupload-rails' gem from the project stops the error when compiling the scss. The 'test-app' compiles just fine with the 'jquery-fileupload-rails' gem, however.

If you have any suggestions for where I might begin to look, I would appreciate the help.

Thanks

**Comment by joelim01** [comment]
It appears that this error was related to a version of the HAML gem. Updating or removing it currently resolves the issue. Closing.
